
# convert fasta file to dictionary
# takes filename as input


def fastaToDict(fil):
    """
    Read fasta-format file fil, return dict of form scaffold:sequence.
    Note: Uses only the unique identifier of each sequence, rather than the 
    entire header, for dict keys. 
    """
    dic = {}
    cur_scaf = ''
    cur_seq = []
    for line in open(fil):
        if line.startswith(">") and cur_scaf == '':
            line = line.split(' ')[0]
            cur_scaf = line.rstrip()
        elif line.startswith(">") and cur_scaf != '':
            dic[cur_scaf] = ''.join(cur_seq)
            line = line.split(' ')[0]
            cur_scaf = line.rstrip()
            cur_seq = []
        else:
            cur_seq.append(line.rstrip())
    dic[cur_scaf] = ''.join(cur_seq)
    return dic

# gene = 'ATGGTGACATTAGACGGTTCCTCACTGACAACGGCGGACGTAGCTCGTGTGCTGTTTGATTTTGAAGAGGCAGCGGCTTCCGCAGAAAGCATGGAGCGTGTGAAAAAGAGCAGAGCAGCAGTGGAACGGATTGTTCAGAAAGAAAAAACAATCTATGGCATTACCACCGGTTTTGGAAAATTCAGTGATGTATTGATTCAAAAAGAAGACGCGGCGGCCCTGCAGCTGAATTTAATTCTTTCTCATGCCTGCGGAGTCGGCGAACCTTTTCCAGAGTCTGTTTCAAGGGCTATGCTGCTTTTACGCGCGAATGCACTGTTAAAAGGTTTTTCCGGTGTACGTGCTGAGCTGATTGAACATTTGCTGGCGTTTTTAAATAAACGTGTCCATCCGGTCATTCCCCAGCAGGGATCACTTGGAGCGAGCGGGGATTTGGCTCCGCTTTCTCATCTGGCGCTTGCGCTGATCGGGCAAGGAGAGGTCTTTTTTGAAGGAGAACGGATGCCGACGATGCAGGCGTTGAAAAAAGCTGGTATTCAGCCGGTCACGCTGACGTCAAAAGAAGGGCTTGCCTTGATTAACGGCACACAGGCCATGACCGCTATGGGCGTCGTCTCTTACATTGAAGCTGAAAAACTAGCCTTTCAATCAGAGCGCATTGCCAGTTTAACGATTGAAGGGCTTCGCGGAATTATGGATGCGTTTGATGAAGATATTCACTCAGCCCGCGGCTATCAGGAACAGATTGATGTGGCAGAACGAATCCGCTTTTACCTGTCAGACAGCAAACTGACGACATCTCAAGGCGAATTGCGGGTGCAGGACGCATATTCACTGCGCTGTATTCCGCAGGTGCACGGTGCGACATGGCAGACGTTAGGCTATGTTAAAGAAAAATTAGAGATTGAGATGAACGCGGCCACAGATAACCCGCTCATTTTCAATGACGGTGACAAAATCATTTCAGGCGGAAACTTTCACGGACAGCCGATCGCCTTTGCAATGGATTTTCTAAAGATTGCAACAGCAGAGCTCGCTAATATTGCGGAGCGCAGAATAGAACGGCTTGTGAATCCGCAGCTGAATGATCTGCCGCCATTCTTAAGCCCTCAGCCCGGCTTGCAATCCGGCGCGATGATTATGCAGTATGCCGCGGCCTCTCTTGTTTCTGAAAATAAAACACTGGCCCATCCCGCGAGTGTGGATTCTATTCCGTCATCCGCCAACCAAGAAGACCACGTCAGCATGGGAACCATCGCTTCAAGGCATGCTTATCAAGTCATTGCCAATACGAGAAGAGTGATTGCGATTGAAGCGATTTGCGCGTTGCAGGCTGTCGAATACAGAGGCATAGAAAACGCAGCCTCTTATACAAAACAGCTTTTTCACGAAATGAGAAAAGTCGTGCCATCCATTCAGCAAGACCGTGTCTTTGCTTATGACATTGAGCATTTGAATGATTGGCTGAAGAAGGAATCTTTTTTGCCAGATCAACAGAATCAAGAACTGATGACAAACTAA'
# def findGenePos(gene):
#     genome = fastaToDict("CBP-1645.fasta").get('>CBP-1645-gff3').lower()
#     print(genome)
#     print(genome.find(gene.lower()))

# findGenePos(gene)